name: Cross

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  x86_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List support target platform
        run: rustup target list

      - name: Build
        run: cargo build -vr

      - name: Run tests
        run: cargo test -vr

      - name: List target
        run: ls -llh target/release

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: x86_linux
          path: |
            target/release/yxy 
            target/release/libyxy.rlib

  x86_win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: List support target platform
        run: rustup target list

      - name: Build
        run: cargo build -vr

      - name: Run tests
        run: cargo test -vr

      - name: List target
        run: ls target/release

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: x86_win
          path: |
            target/release/*yxy*
