name: Cross

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  x86_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Install target support
      #   run: rustup target add ${{matrix.platform}}

      - name: List support target platform
        run: rustup target list

      - name: Build
        run: cargo build -vr

      - name: Run tests
        run: cargo test -vr

      - name: List target
        run: ls -llh target

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: x86_linux
          path: target/
