name: Cross

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["x86_64-unknown-linux-musl", "x86_64-unknown-linux-gnu"]

    steps:
      - uses: actions/checkout@v3

      - name: List support target platform
        run: rustup target list

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: cross build -vr --target ${{matrix.platform}}

      - name: Run tests
        run: cross test -vr --target ${{matrix.platform}}

      - name: List target
        run: ls -llh target

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{matrix.platform}}
          path: target/
